name: Lint code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check cmake
        shell: bash
        run: cmake --version

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Lint with ruff
        run: uv run ruff check
